M48
; DRILL file {KiCad 9.0.5} date 2026-09-14T21:20:42-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-14T21:20:42-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.020
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X2.5Y-22.94
X8.5Y-22.94
X35.0Y-7.14
X53.0Y-7.14
X104.94Y-19.0
X104.94Y-34.0
T2
X4.0Y-4.0
X4.0Y-42.0
X106.0Y-4.0
X106.0Y-42.0
M30
